//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestPhanQuyen_WPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRole_PhanQuyen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserRole_PhanQuyen()
        {
            this.Users_PhanQuyen = new HashSet<Users_PhanQuyen>();
        }
    
        public int Id { get; set; }
        public string DisplayName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Users_PhanQuyen> Users_PhanQuyen { get; set; }
    }
}
